bower-install-simple:
  options:
    directory: support
    cwd: lib/wanted/auto-load-images

concat:
  src:
    - lib/wanted/auto-load-images/support/ajaxq/ajaxq.js
    - lib/wanted/auto-load-images/auto-load-images.js
  dest: dist/auto-load-images.js
  options:
    banner: |
      // ==UserScript==
      // @name         <%= autoLoadImages.pkg.name %>
      // @namespace    <%= namespace %>
      // @homepage     <%= pkg.homepage %>
      // @version      <%= autoLoadImages.pkg.version %>
      // @description  <%= autoLoadImages.pkg.description %>
      // @author       <%= pkg.author %>
      // @downloadURL  https://raw.githubusercontent.com/boneskull/bricklink-scripts/master/dist/auto-load-images.js
      // @updateURL    https://raw.githubusercontent.com/boneskull/bricklink-scripts/master/dist/auto-load-images.meta.js
      // @include      http://www.bricklink.com/wantedAddDetail.asp?*
      // @require      //code.jquery.com/jquery-1.11.1.min.js
      // @require      //cdnjs.cloudflare.com/ajax/libs/spin.js/2.0.1/jquery.spin.min.js
      // ==/UserScript==

write:
  dist/auto-load-images.meta.js: <%= concat['auto-load-images'].options.banner %>
